//
// Created by fanyiran on 2019-07-15.
//

#ifndef FFMPEGVIDEO_FFMPEG_STATUS_H
#define FFMPEGVIDEO_FFMPEG_STATUS_H

enum Status {
    STATUS_UNKNOW,
    STATUS_INIT,
    STATUS_START,
    STATUS_RELEASE,
    STATUS_ERROR,
};
#endif //FFMPEGVIDEO_FFMPEG_STATUS_H
